In [51]:
import pandas as pd 
import numpy as np

In [52]:
def GM11(x0):  # 自写GM11函数
    x1 = np.cumsum(x0)
    z1 = (x1[:len(x1)-1] + x1[1:]) / 2.0
    z1 = z1.reshape(len(z1),1)
    B  = np.append(-z1,np.ones_like(z1),axis=1)
    Yn = x0[1:].reshape(len(x0)-1,1)
    [[a],[b]] = np.dot(np.dot(np.linalg.inv(np.dot(B.T,B)),B.T),Yn)
    f = lambda k : (x0[0]- b/a) * np.exp(-a*(k-1)) - (x0[0]-b/a) * np.exp(-a * (k-2))
    delta = np.abs(x0 - np.array([f(i)  for i in range(1,len(x0)+1)]))
    C = delta.std() / x0.std()
    P = 1.0 * (np.abs(delta - delta.mean())< 0.6745 * x0.std() ).sum()/len(x0)
    
    return f,a,b,x0[0],C,P

In [53]:
data = pd.read_csv('lasso_data1.csv')
data_tol = pd.read_csv('data.csv')

In [54]:
data.index = range(1994,2014)
data.index
data.loc[2014] = None
data.loc[2015] = None
data

,x1,x3,x4,x5,x6,x7,x8,x13
1994,3831732.0,448.19,7571.00,6212.70,6370241.0,525.71,985.31,5321.0
1995,3913824.0,549.97,9038.16,7601.73,6467115.0,618.25,1259.20,6529.0
1996,3928907.0,686.44,9905.31,8092.82,6560508.0,638.94,1468.06,7008.0
1997,4282130.0,802.59,10444.60,8767.98,6664862.0,656.58,1678.12,7694.0
1998,4453911.0,904.57,11255.70,9422.33,6741400.0,758.83,1893.52,8027.0
1999,4548852.0,1000.69,12018.52,9751.44,6850024.0,878.26,2139.18,8549.0
2000,4962579.0,1121.13,13966.53,11349.47,7006896.0,923.67,2492.74,9566.0
2001,5029338.0,1248.29,14694.00,11467.35,7125979.0,978.21,2841.65,10473.0
2002,5070216.0,1370.68,13380.47,10671.78,7206229.0,1009.24,3203.96,11469.0
2003,5210706.0,1494.27,15002.59,11570.58,7251888.0,1175.17,3758.62,12360.0
2004,5407087.0,1677.77,16884.16,13120.83,7376720.0,1348.93,4450.55,14174.0
2005,5744550.0,1905.84,18287.24,14468.24,7505322.0,1519.16,5154.23,16394.0
2006,5994973.0,2199.14,19850.66,15444.93,7607220.0,1696.38,6081.86,17881.0
2007,6236312.0,2624.24,22469.22,18951.32,7734787.0,1863.34,7140.32,20058.0
2008,6529045.0,3187.39,25316.72,20835.95,7841695.0,2105.54,8287.38,22114.0
2009,6791495.0,3615.77,27609.59,22820.89,7946154.0,2659.85,9138.21,24190.0
2010,7110695.0,4476.38,30658.49,25011.61,8061370.0,3263.57,10748.28,29549.0
2011,7431755.0,5243.03,34438.08,28209.74,8145797.0,3412.21,12423.44,34214.0
2012,7512997.0,5977.27,38053.52,30490.44,8222969.0,3758.39,13551.21,37934.0
2013,7599295.0,6882.85,42049.14,33156.83,8323096.0,4454.55,15420.14,41972.0
2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
for i in data.columns:
    f = GM11(data.loc[range(1994,2014),i].values)[0]
    data.loc[2014,i] = f(len(data)-1)
    data.loc[2015,i] = f(len(data))
    data[i] = data[i].round(2)

In [56]:
data

,x1,x3,x4,x5,x6,x7,x8,x13
1994,3831732.00,448.19,7571.00,6212.70,6370241.00,525.71,985.31,5321.00
1995,3913824.00,549.97,9038.16,7601.73,6467115.00,618.25,1259.20,6529.00
1996,3928907.00,686.44,9905.31,8092.82,6560508.00,638.94,1468.06,7008.00
1997,4282130.00,802.59,10444.60,8767.98,6664862.00,656.58,1678.12,7694.00
1998,4453911.00,904.57,11255.70,9422.33,6741400.00,758.83,1893.52,8027.00
1999,4548852.00,1000.69,12018.52,9751.44,6850024.00,878.26,2139.18,8549.00
2000,4962579.00,1121.13,13966.53,11349.47,7006896.00,923.67,2492.74,9566.00
2001,5029338.00,1248.29,14694.00,11467.35,7125979.00,978.21,2841.65,10473.00
2002,5070216.00,1370.68,13380.47,10671.78,7206229.00,1009.24,3203.96,11469.00
2003,5210706.00,1494.27,15002.59,11570.58,7251888.00,1175.17,3758.62,12360.00
2004,5407087.00,1677.77,16884.16,13120.83,7376720.00,1348.93,4450.55,14174.00
2005,5744550.00,1905.84,18287.24,14468.24,7505322.00,1519.16,5154.23,16394.00
2006,5994973.00,2199.14,19850.66,15444.93,7607220.00,1696.38,6081.86,17881.00
2007,6236312.00,2624.24,22469.22,18951.32,7734787.00,1863.34,7140.32,20058.00
2008,6529045.00,3187.39,25316.72,20835.95,7841695.00,2105.54,8287.38,22114.00
2009,6791495.00,3615.77,27609.59,22820.89,7946154.00,2659.85,9138.21,24190.00
2010,7110695.00,4476.38,30658.49,25011.61,8061370.00,3263.57,10748.28,29549.00
2011,7431755.00,5243.03,34438.08,28209.74,8145797.00,3412.21,12423.44,34214.00
2012,7512997.00,5977.27,38053.52,30490.44,8222969.00,3758.39,13551.21,37934.00
2013,7599295.00,6882.85,42049.14,33156.83,8323096.00,4454.55,15420.14,41972.00
2014,8142148.24,7042.31,43611.84,35046.63,8505522.58,4600.40,18686.28,44506.47
2015,8460489.28,8166.92,47792.22,38384.22,8627139.31,5214.78,21474.47,49945.88

In [57]:
y = list(data_tol['y'].values)
y.extend([np.nan,np.nan])
data['y'] = y
data

,x1,x3,x4,x5,x6,x7,x8,x13,y
1994,3831732.00,448.19,7571.00,6212.70,6370241.00,525.71,985.31,5321.00,64.87
1995,3913824.00,549.97,9038.16,7601.73,6467115.00,618.25,1259.20,6529.00,99.75
1996,3928907.00,686.44,9905.31,8092.82,6560508.00,638.94,1468.06,7008.00,88.11
1997,4282130.00,802.59,10444.60,8767.98,6664862.00,656.58,1678.12,7694.00,106.07
1998,4453911.00,904.57,11255.70,9422.33,6741400.00,758.83,1893.52,8027.00,137.32
1999,4548852.00,1000.69,12018.52,9751.44,6850024.00,878.26,2139.18,8549.00,188.14
2000,4962579.00,1121.13,13966.53,11349.47,7006896.00,923.67,2492.74,9566.00,219.91
2001,5029338.00,1248.29,14694.00,11467.35,7125979.00,978.21,2841.65,10473.00,271.91
2002,5070216.00,1370.68,13380.47,10671.78,7206229.00,1009.24,3203.96,11469.00,269.10
2003,5210706.00,1494.27,15002.59,11570.58,7251888.00,1175.17,3758.62,12360.00,300.55
2004,5407087.00,1677.77,16884.16,13120.83,7376720.00,1348.93,4450.55,14174.00,338.45
2005,5744550.00,1905.84,18287.24,14468.24,7505322.00,1519.16,5154.23,16394.00,408.86
2006,5994973.00,2199.14,19850.66,15444.93,7607220.00,1696.38,6081.86,17881.00,476.72
2007,6236312.00,2624.24,22469.22,18951.32,7734787.00,1863.34,7140.32,20058.00,838.99
2008,6529045.00,3187.39,25316.72,20835.95,7841695.00,2105.54,8287.38,22114.00,843.14
2009,6791495.00,3615.77,27609.59,22820.89,7946154.00,2659.85,9138.21,24190.00,1107.67
2010,7110695.00,4476.38,30658.49,25011.61,8061370.00,3263.57,10748.28,29549.00,1399.16
2011,7431755.00,5243.03,34438.08,28209.74,8145797.00,3412.21,12423.44,34214.00,1535.14
2012,7512997.00,5977.27,38053.52,30490.44,8222969.00,3758.39,13551.21,37934.00,1579.68
2013,7599295.00,6882.85,42049.14,33156.83,8323096.00,4454.55,15420.14,41972.00,2088.14
2014,8142148.24,7042.31,43611.84,35046.63,8505522.58,4600.40,18686.28,44506.47,NaN
2015,8460489.28,8166.92,47792.22,38384.22,8627139.31,5214.78,21474.47,49945.88,NaN

In [59]:
gm_data = data.to_csv('gm_data.csv')